export interface BossStageConfig {
  stageId: number // 1 to 15
  chapterId: number // 1 to 5
  name: string
  bossName: string
  bossAvatar: string
  bossPokemonId: number
  powerLevel: number
  title: string
  quote: string
  storylineIntro: string
  dialoguePreMatch: string
  dialogueWin: string
  dialogueLose: string
  bossSkillName: string
  bossSkillIcon: string
  bossSkillDesc: string
  bossSkillInterval: number // in seconds
  moveDelayMin: number
  moveDelayMax: number
  rewardCoins: number
  targetTime: number // in seconds
  chapterEnvEffect: 'electro-storm' | 'magma-fire' | 'glacial-frost' | 'shadow-void' | 'astral-cosmic'
}

export interface CampaignChapter {
  id: number
  title: string
  subtitle: string
  locationName: string
  badge: string
  accentColor: string
  glowColor: string
  bgGradient: string
  envEffect: 'electro-storm' | 'magma-fire' | 'glacial-frost' | 'shadow-void' | 'astral-cosmic'
  storySummary: string
  stages: BossStageConfig[]
  completionRewardTitle: string
  completionRewardCoins: number
}

export const CAMPAIGN_CHAPTERS: CampaignChapter[] = [
  {
    id: 1,
    title: 'Chương 1: Khởi Nguyên Kanto',
    subtitle: 'Bão Điện Thung Lũng Sấm Sét',
    locationName: 'Rừng Rậm Viridian & Thung Lũng Điện',
    badge: '⚡',
    accentColor: '#facc15',
    glowColor: 'rgba(250, 204, 21, 0.45)',
    bgGradient: 'radial-gradient(circle at 50% 30%, rgba(20, 45, 25, 0.92) 0%, rgba(5, 20, 15, 0.98) 100%)',
    envEffect: 'electro-storm',
    storySummary: 'Nguồn năng lượng từ viên Đá Sấm Sét cổ xưa bị phong ấn tại thung lũng Viridian đang mất kiểm soát. Các loài Pokémon Sấm Sét trở nên cuồng bạo dưới sự dẫn dắt của Pikachu Hắc Ám. Satoshi và các Trainer phải hợp lực giải phóng kết giới!',
    completionRewardTitle: '⚡ Bậc Thầy Sấm Sét Kanto',
    completionRewardCoins: 200,
    stages: [
      {
        stageId: 1,
        chapterId: 1,
        name: 'Ải 1: Sâu Gai & Pidgey Tuần Tra',
        bossName: 'Caterpie & Pidgey Tinh Nhanh',
        bossAvatar: '🐛',
        bossPokemonId: 10,
        powerLevel: 1500,
        title: 'Lính Gác Rừng Rậm',
        quote: 'Kẻ xâm nhập vùng cấm địa sấm sét sẽ không thể vượt qua chúng ta!',
        storylineIntro: 'Bước chân vào cửa ngõ thung lũng Viridian, bầy Pokémon tuần tra lập tức bao vây nhằm cản đường bạn!',
        dialoguePreMatch: 'Chúng ta sẽ thử thách tốc độ quan sát của ngươi trước khi tiến sâu vào rừng!',
        dialogueWin: 'Ngươi nối cờ nhanh quá... hãy cẩn thận với Vịt Psyduck phía trước!',
        dialogueLose: 'Rừng sấm sét không dành cho những kẻ chậm tay!',
        bossSkillName: 'Bẫy Gai Tơ',
        bossSkillIcon: '🕸️',
        bossSkillDesc: 'Làm chậm tốc độ nhận diện gợi ý 3s',
        bossSkillInterval: 18,
        moveDelayMin: 4500,
        moveDelayMax: 5800,
        rewardCoins: 50,
        targetTime: 240,
        chapterEnvEffect: 'electro-storm',
      },
      {
        stageId: 2,
        chapterId: 1,
        name: 'Ải 2: Vịt Psyduck Đau Đầu',
        bossName: 'Psyduck Cuồng Trí',
        bossAvatar: '🦆',
        bossPokemonId: 54,
        powerLevel: 2800,
        title: 'Hộ Vệ Thủy Lôi',
        quote: 'Đầu ta... đầu ta sắp nổ tung vì sóng điện rồi quaaaak!',
        storylineIntro: 'Vịt Psyduck bị sóng điện từ kích thích não bộ cực độ, phát ra năng lượng tâm linh bối rối khiến bàn cờ bị chao đảo!',
        dialoguePreMatch: 'Quáaaak! Đừng làm ồn nữa, não ta đau quá!',
        dialogueWin: 'Cảm ơn ngươi... đầu ta đã hết đau rồi!',
        dialogueLose: 'Sóng não của ta đã làm ngươi rối mắt chưa? Quaaak!',
        bossSkillName: 'Sóng Não Bối Rối',
        bossSkillIcon: '🌀',
        bossSkillDesc: 'Đảo nhẹ 2 cặp cờ trên bàn',
        bossSkillInterval: 16,
        moveDelayMin: 3800,
        moveDelayMax: 5000,
        rewardCoins: 75,
        targetTime: 220,
        chapterEnvEffect: 'electro-storm',
      },
      {
        stageId: 3,
        chapterId: 1,
        name: 'Ải 3 (BOSS CHƯƠNG): Dark Pikachu',
        bossName: 'Dark Pikachu (Sấm Sét Điên Loạn)',
        bossAvatar: '⚡',
        bossPokemonId: 25,
        powerLevel: 6500,
        title: 'Chúa Tể Thung Lũng Sấm Sét',
        quote: 'PIKAAA... CHUUUUU! Hãy nếm mùi điện áp 10 Vạn Volt hủy diệt!',
        storylineIntro: 'Ngự trị trên đỉnh Cột Lôi Đình, Dark Pikachu tỏa ra luồng sấm đen hủy diệt. Đánh bại nó để giải phóng kết giới Chương 1!',
        dialoguePreMatch: 'Ngươi muốn cứu thung lũng này sao? Hãy chứng kiến sấm sét bóng đêm của ta!',
        dialogueWin: 'Pika... ngươi đã thanh tẩy được nguồn điện bóng đêm...',
        dialogueLose: 'Ha ha! Sức mạnh của sấm sét thuộc về ta!',
        bossSkillName: 'Sấm Sét 10 Vạn Volt Đen',
        bossSkillIcon: '⚡',
        bossSkillDesc: 'Phóng tia sét làm tê liệt bàn cờ 2s',
        bossSkillInterval: 14,
        moveDelayMin: 3000,
        moveDelayMax: 4200,
        rewardCoins: 120,
        targetTime: 200,
        chapterEnvEffect: 'electro-storm',
      },
    ],
  },
  {
    id: 2,
    title: 'Chương 2: Hỏa Long Phẫn Nộ',
    subtitle: 'Đỉnh Núi Lửa Hoang Tàn & Nham Thạch',
    locationName: 'Miệng Núi Lửa Cinder Peak',
    badge: '🔥',
    accentColor: '#f97316',
    glowColor: 'rgba(249, 115, 22, 0.45)',
    bgGradient: 'radial-gradient(circle at 50% 30%, rgba(45, 20, 10, 0.94) 0%, rgba(20, 5, 5, 0.98) 100%)',
    envEffect: 'magma-fire',
    storySummary: 'Dấn thân vào miệng núi lửa Cinder Peak ngùn ngụt nham thạch, nơi Rồng Lửa Charizard bị Ma Khí thiêu đốt tâm trí. Sức nóng bốc cháy thiêu rụi thời gian, đòi hỏi phản xạ cực nhanh để sống sót!',
    completionRewardTitle: '🔥 Dũng Sĩ Hỏa Long Charizard',
    completionRewardCoins: 250,
    stages: [
      {
        stageId: 4,
        chapterId: 2,
        name: 'Ải 4: Hồ Ly Vulpix Lửa Hồng',
        bossName: 'Cáo Lửa Vulpix',
        bossAvatar: '🦊',
        bossPokemonId: 37,
        powerLevel: 8200,
        title: 'Lính Canh Lò Lửa',
        quote: 'Lửa hồng chín đuôi sẽ soi rọi từng nước đi của ngươi!',
        storylineIntro: 'Không khí bắt đầu đặc quánh khói bụi than hồng. Hồ Ly Vulpix xuất hiện múa lửa quanh các ô quân bài Pokémon.',
        dialoguePreMatch: 'Cẩn thận kẻo bị bỏng tay trước ngọn lửa cửu vĩ nhé!',
        dialogueWin: 'Lửa của ta đã bị trí tuệ của ngươi dập tắt!',
        dialogueLose: 'Tro tàn chính là điểm dừng chân của ngươi!',
        bossSkillName: 'Màn Lửa Than Hồng',
        bossSkillIcon: '🔥',
        bossSkillDesc: 'Làm chói mắt tạm thời 1.5s',
        bossSkillInterval: 16,
        moveDelayMin: 3400,
        moveDelayMax: 4400,
        rewardCoins: 70,
        targetTime: 210,
        chapterEnvEffect: 'magma-fire',
      },
      {
        stageId: 5,
        chapterId: 2,
        name: 'Ải 5: Thằn Lằn Magmar Bỏng Rát',
        bossName: 'Magmar Dung Nham',
        bossAvatar: '🦎',
        bossPokemonId: 126,
        powerLevel: 12000,
        title: 'Hộ Vệ Miệng Núi Lửa',
        quote: 'Dung nham 1200 độ C sẽ nung chảy mọi quân cờ cản bước!',
        storylineIntro: 'Magmar nổi lên từ hồ dung nham sôi sùng sục, ném từng quả cầu lửa thiêu đốt bàn cờ.',
        dialoguePreMatch: 'Nóng quá phải không? Càng nóng thì càng dễ nối sai đấy!',
        dialogueWin: 'Dung nham nguội mất rồi... ngươi thật kiên cường!',
        dialogueLose: 'Biến thành tro bụi dung nham đi!',
        bossSkillName: 'Phun Trào Nham Thạch',
        bossSkillIcon: '🌋',
        bossSkillDesc: 'Thiêu đốt trừ 2 giây thời gian',
        bossSkillInterval: 15,
        moveDelayMin: 2900,
        moveDelayMax: 3900,
        rewardCoins: 90,
        targetTime: 190,
        chapterEnvEffect: 'magma-fire',
      },
      {
        stageId: 6,
        chapterId: 2,
        name: 'Ải 6 (BOSS CHƯƠNG): Charizard Hỏa Thần',
        bossName: 'Charizard Hỏa Long Vương',
        bossAvatar: '🐉',
        bossPokemonId: 6,
        powerLevel: 18500,
        title: 'Chúa Tể Bão Lửa Núi Cinder',
        quote: 'GÀOOOO! Tiếng gầm của Rồng Lửa sẽ xé toạc bầu trời này!',
        storylineIntro: 'Đôi cánh lửa khổng lồ giương cao trên đỉnh núi lửa! Charizard Hỏa Thần gầm thét, tung chiêu Bão Lửa Thiên Thể thiêu đốt mọi vật cản!',
        dialoguePreMatch: 'Hãy chứng minh ngươi xứng đáng được đứng trước ngai vàng Hỏa Long!',
        dialogueWin: 'Ngươi... quả thực sở hữu ngọn lửa nhiệt huyết thuần khiết!',
        dialogueLose: 'Ngươi chưa đủ tư cách vượt qua Đỉnh Cinder!',
        bossSkillName: 'Bão Lửa Thiên Thần Hỏa',
        bossSkillIcon: '🔥',
        bossSkillDesc: 'Khạc lửa thiêu đốt -3s thời gian nếu không nối nhanh',
        bossSkillInterval: 12,
        moveDelayMin: 2300,
        moveDelayMax: 3300,
        rewardCoins: 150,
        targetTime: 180,
        chapterEnvEffect: 'magma-fire',
      },
    ],
  },
  {
    id: 3,
    title: 'Chương 3: Băng Tuyết Vĩnh Cửu',
    subtitle: 'Động Hàn Băng Vô Tận & Bão Tuyết Articuno',
    locationName: 'Hang Động Băng Seafoam Caverns',
    badge: '❄️',
    accentColor: '#38bdf8',
    glowColor: 'rgba(56, 189, 248, 0.45)',
    bgGradient: 'radial-gradient(circle at 50% 30%, rgba(10, 30, 50, 0.94) 0%, rgba(5, 15, 25, 0.98) 100%)',
    envEffect: 'glacial-frost',
    storySummary: 'Từ đỉnh núi lửa bỏng rát, hành trình dẫn lối vào lòng hang động Băng Vĩnh Cửu nghìn năm. Thần thú Articuno đang ngủ say bỗng thức giấc bởi dị tượng, biến toàn bộ không gian thành tinh thể băng vỡ vụn.',
    completionRewardTitle: '❄️ Bậc Thầy Băng Giá Articuno',
    completionRewardCoins: 300,
    stages: [
      {
        stageId: 7,
        chapterId: 3,
        name: 'Ải 7: Rùa Nước & Hải Cẩu Seel',
        bossName: 'Squirtle & Seel Băng Tinh',
        bossAvatar: '🦭',
        bossPokemonId: 86,
        powerLevel: 22000,
        title: 'Tuần Binh Lãnh Nguyên',
        quote: 'Sàn băng trơn trượt lắm đó, hãy cẩn thận trượt tay!',
        storylineIntro: 'Những lớp băng bóng loáng phủ kín mặt sàn. Bầy thú băng bơi lội dưới làn nước giá buốt thách thức bạn.',
        dialoguePreMatch: 'Đường nối trên băng sẽ trơn tuột như cá bơi!',
        dialogueWin: 'Tay ngươi vững vàng thật đấy, không hề bị trượt chút nào!',
        dialogueLose: 'Ngươi đã trượt chân trên tảng băng trôi rồi!',
        bossSkillName: 'Bọt Nước Trơn Trượt',
        bossSkillIcon: '🫧',
        bossSkillDesc: 'Làm rung nhẹ bảng cờ',
        bossSkillInterval: 17,
        moveDelayMin: 2800,
        moveDelayMax: 3800,
        rewardCoins: 80,
        targetTime: 200,
        chapterEnvEffect: 'glacial-frost',
      },
      {
        stageId: 8,
        chapterId: 3,
        name: 'Ải 8: Rồng Nước Gyarados Cuồng Bạo',
        bossName: 'Gyarados Thủy Quái',
        bossAvatar: '🌊',
        bossPokemonId: 130,
        powerLevel: 28000,
        title: 'Thủy Thần Vực Băng',
        quote: 'GAAAAHHH! Cơn sóng thần băng giá sẽ chôn vùi ngươi!',
        storylineIntro: 'Một tiếng nổ rền vang, Gyarados khổng lồ phá vỡ mặt băng lao lên, tạo nên những cơn bão tuyết mù mịt!',
        dialoguePreMatch: 'Đại hồng thủy băng giá sẽ nuốt chửng mọi cặp cờ!',
        dialogueWin: 'Thủy triều đã rút... ngươi đánh bại được cơn cuồng nộ của ta!',
        dialogueLose: 'Chìm sâu xuống đáy vực băng đi!',
        bossSkillName: 'Sóng Thần Băng Cuộn',
        bossSkillIcon: '🌊',
        bossSkillDesc: 'Tạo mù sương làm mờ bảng cờ 2s',
        bossSkillInterval: 14,
        moveDelayMin: 2400,
        moveDelayMax: 3400,
        rewardCoins: 110,
        targetTime: 180,
        chapterEnvEffect: 'glacial-frost',
      },
      {
        stageId: 9,
        chapterId: 3,
        name: 'Ải 9 (BOSS CHƯƠNG): Articuno Phượng Hoàng Băng',
        bossName: 'Articuno Băng Tinh Vũ',
        bossAvatar: '🦅',
        bossPokemonId: 144,
        powerLevel: 36000,
        title: 'Thần Thú Băng Giá Huyền Thoại',
        quote: 'Cánh tuyết thần linh sẽ ngưng đọng thời gian của trần thế!',
        storylineIntro: 'Cung điện băng pha lê mở ra! Chim Băng Articuno sải cánh lấp lánh bụi kim cương, đóng băng mọi dòng chảy thời gian.',
        dialoguePreMatch: 'Hơi thở của Băng Giá Vĩnh Hằng sẽ thử thách sự nhẫn nại của ngươi!',
        dialogueWin: 'Ánh sáng trái tim ngươi đã làm tan chảy băng giá nghìn năm...',
        dialogueLose: 'Ngươi đã trở thành một bức tượng băng vĩnh cửu!',
        bossSkillName: 'Bão Tuyết Tuyệt Đối Zero',
        bossSkillIcon: '❄️',
        bossSkillDesc: 'Đóng băng bảng cờ 2.5s',
        bossSkillInterval: 12,
        moveDelayMin: 2000,
        moveDelayMax: 3000,
        rewardCoins: 180,
        targetTime: 170,
        chapterEnvEffect: 'glacial-frost',
      },
    ],
  },
  {
    id: 4,
    title: 'Chương 4: Ảo Ảnh Vực Sâu',
    subtitle: 'Rừng Ma Quái Tsukuyomi & Ảo Thuật Susanoo',
    locationName: 'Vực Thẳm Tsukuyomi & Tháp U Minh',
    badge: '☄️',
    accentColor: '#dc2626',
    glowColor: 'rgba(220, 38, 38, 0.45)',
    bgGradient: 'radial-gradient(circle at 50% 30%, rgba(35, 10, 40, 0.94) 0%, rgba(15, 5, 20, 0.98) 100%)',
    envEffect: 'shadow-void',
    storySummary: 'Không gian bị bẻ cong bởi Đồng Thuật Vạn Hoa Đồng Sharingan của Uchiha Madara và Gengar Hắc Ám. Bàn cờ biến chuyển dị thường, trọng lực bị đảo lộn trong thế giới ảo mộng hư vô!',
    completionRewardTitle: '☄️ Huyền Thoại Tsukuyomi Vực Sâu',
    completionRewardCoins: 350,
    stages: [
      {
        stageId: 10,
        chapterId: 4,
        name: 'Ải 10: Ma Trơi Gastly & Haunter Hư Vô',
        bossName: 'Haunter Hư Vô',
        bossAvatar: '👻',
        bossPokemonId: 93,
        powerLevel: 42000,
        title: 'Hồn Ma Cõi Âm',
        quote: 'Hi hi hi... nhìn thấy ta không? Hay chỉ là ảo giác?',
        storylineIntro: 'Sương mù tím che phủ tầm mắt. Những bóng ma cười cợt trồi lên từ hư vô, thoắt ẩn thoắt hiện trên bảng cờ.',
        dialoguePreMatch: 'Coi chừng nối trúng cái bóng của chính ngươi đấy, hi hi!',
        dialogueWin: 'Ái chà, bắt bài ma quái nhanh thế!',
        dialogueLose: 'Lạc vào mê cung u hồn muôn đời nhé, hi hi hi!',
        bossSkillName: 'Ảo Ảnh Ma Quái',
        bossSkillIcon: '👻',
        bossSkillDesc: 'Khói ma quái làm mờ 3 ô ngẫu nhiên',
        bossSkillInterval: 15,
        moveDelayMin: 2200,
        moveDelayMax: 3100,
        rewardCoins: 100,
        targetTime: 180,
        chapterEnvEffect: 'shadow-void',
      },
      {
        stageId: 11,
        chapterId: 4,
        name: 'Ải 11: Gengar Chúa Tể Bóng Đêm',
        bossName: 'Gengar Ác Mộng',
        bossAvatar: '😈',
        bossPokemonId: 94,
        powerLevel: 50000,
        title: 'Bóng Đêm Cực Tà',
        quote: 'Nuốt chửng giấc mơ! Bàn cờ của ngươi sẽ bị bóng đêm ăn mòn!',
        storylineIntro: 'Nụ cười đỏ như máu hiện ra trong bóng tối! Gengar bước ra từ chiếc bóng của bạn, chuẩn bị nuốt trọn chiến thắng!',
        dialoguePreMatch: 'Hãy nếm thử Ác Mộng Đen Tối của ta!',
        dialogueWin: 'Ặc... ánh sáng chiếu rọi bóng tối rồi!',
        dialogueLose: 'Cái bóng của ngươi giờ thuộc về ta!',
        bossSkillName: 'Bóng Ma Hắc Ám',
        bossSkillIcon: '😈',
        bossSkillDesc: 'Xáo trộn 4 ô cờ xung quanh',
        bossSkillInterval: 13,
        moveDelayMin: 1800,
        moveDelayMax: 2600,
        rewardCoins: 140,
        targetTime: 160,
        chapterEnvEffect: 'shadow-void',
      },
      {
        stageId: 12,
        chapterId: 4,
        name: 'Ải 12 (BOSS CHƯƠNG): Uchiha Madara Susanoo',
        bossName: 'Uchiha Madara (Thần Thể Susanoo)',
        bossAvatar: '☄️',
        bossPokemonId: 491,
        powerLevel: 68000,
        title: 'Huyền Thoại Gia Tộc Uchiha',
        quote: 'Ngươi cũng biết múa đấy chứ? Nhưng trước Susanoo toàn năng, tất cả chỉ là cát bụi!',
        storylineIntro: 'Mặt trăng máu Tsukuyomi rực đỏ bầu trời! Khổng lồ Susanoo bọc giáp thần thánh giáng lâm, tạo lực hút dồn nén toàn bộ quân cờ xuống vực thẳm!',
        dialoguePreMatch: 'Hãy chứng kiến sức mạnh đích thực của Thần Linh!',
        dialogueWin: 'Khá khen cho ngươi... có thể đứng vững trước ảo thuật của ta!',
        dialogueLose: 'Sức mạnh này không phải thứ ngươi có thể chạm tới!',
        bossSkillName: 'Ảo Thuật Tsukuyomi & Trọng Lực',
        bossSkillIcon: '☄️',
        bossSkillDesc: 'Dồn cờ và đảo vị trí 2 cặp cờ',
        bossSkillInterval: 11,
        moveDelayMin: 1500,
        moveDelayMax: 2200,
        rewardCoins: 220,
        targetTime: 150,
        chapterEnvEffect: 'shadow-void',
      },
    ],
  },
  {
    id: 5,
    title: 'Chương 5: Vực Thẩm Tối Thượng',
    subtitle: 'Đền Thờ Mewtwo & Tinh Tú Ngân Hà Astral',
    locationName: 'Quỹ Đạo Tinh Vân Tối Thượng (Astral Sanctuary)',
    badge: '🔮',
    accentColor: '#c026d3',
    glowColor: 'rgba(192, 38, 211, 0.45)',
    bgGradient: 'radial-gradient(circle at 50% 30%, rgba(25, 10, 45, 0.96) 0%, rgba(5, 5, 20, 0.99) 100%)',
    envEffect: 'astral-cosmic',
    storySummary: 'Chuyến tàu Astral Express đưa bạn bay xuyên qua dải Ngân Hà rực rỡ đến Thánh Đường Tinh Tú. Nơi đây, Mewtwo Thức Tỉnh đang chờ đợi trận chiến cuối cùng định đoạt vận mệnh của Bậc Thầy Pikachu!',
    completionRewardTitle: '👑 BẬC THẦY TỐI THƯỢNG PIKACHU',
    completionRewardCoins: 500,
    stages: [
      {
        stageId: 13,
        chapterId: 5,
        name: 'Ải 13: Sấm Dragonite Thần Tốc',
        bossName: 'Dragonite Tinh Vân',
        bossAvatar: '⚡',
        bossPokemonId: 149,
        powerLevel: 75000,
        title: 'Long Thần Thiên Giới',
        quote: 'Tốc độ âm thanh vượt vũ trụ! Ngươi có bắt kịp ta không?',
        storylineIntro: 'Giữa đại dương sao băng lấp lánh, Dragonite khổng lồ bay lượn với tốc độ ánh sáng, dẫn dắt các dòng chảy ma pháp tinh tú.',
        dialoguePreMatch: 'Đôi cánh thiên thần sẽ lướt qua mọi nước đi của ngươi!',
        dialogueWin: 'Tốc độ kết nối của ngươi quả thực vượt qua cả ánh sáng!',
        dialogueLose: 'Chậm một bước là lỡ cả dải ngân hà!',
        bossSkillName: 'Long Thần Lôi Quang',
        bossSkillIcon: '⚡',
        bossSkillDesc: 'Tăng tốc di chuyển của Boss',
        bossSkillInterval: 14,
        moveDelayMin: 1600,
        moveDelayMax: 2200,
        rewardCoins: 130,
        targetTime: 160,
        chapterEnvEffect: 'astral-cosmic',
      },
      {
        stageId: 14,
        chapterId: 5,
        name: 'Ải 14: Chim Lửa Bất Tử Moltres',
        bossName: 'Moltres Tinh Tú Bất Tử',
        bossAvatar: '🦅',
        bossPokemonId: 146,
        powerLevel: 88000,
        title: 'Phượng Hoàng Lửa Bất Tử',
        quote: 'Ngọn lửa Astral bất diệt! Tro tàn sẽ lại tái sinh!',
        storylineIntro: 'Cột lửa đỏ vàng rực rỡ bùng lên giữa khoảng không vô trọng lực! Moltres sải cánh tạo nên những chùm mưa sao băng rực lửa.',
        dialoguePreMatch: 'Hãy vượt qua ngọn lửa tái sinh của phượng hoàng!',
        dialogueWin: 'Ngọn lửa nhiệt huyết của ngươi đã chinh phục được ta!',
        dialogueLose: 'Hãy thiêu đốt trong ngọn lửa vũ trụ vĩnh cửu!',
        bossSkillName: 'Sao Băng Tái Sinh',
        bossSkillIcon: '🔥',
        bossSkillDesc: 'Thiêu đốt thời gian -2s',
        bossSkillInterval: 12,
        moveDelayMin: 1300,
        moveDelayMax: 1900,
        rewardCoins: 160,
        targetTime: 150,
        chapterEnvEffect: 'astral-cosmic',
      },
      {
        stageId: 15,
        chapterId: 5,
        name: 'Ải 15 (ĐẠI BOSS TỐI THƯỢNG): Mewtwo Thức Tỉnh',
        bossName: 'Mewtwo Tối Thượng (Awakened Psy)',
        bossAvatar: '🔮',
        bossPokemonId: 150,
        powerLevel: 99999,
        title: 'Đấng Thao Túng Tâm Linh Vũ Trụ',
        quote: 'Ta không được tạo ra để phục tùng. Ta sinh ra để thống trị vũ trụ này!',
        storylineIntro: 'Ngai vàng tối thượng tỏa sáng rực rỡ giữa vòng xoáy tinh vân! Mewtwo giơ bàn tay năng lượng tâm linh, bẻ cong thời không và ma trận quân bài!',
        dialoguePreMatch: 'Hãy cho ta thấy ý chí sắt đá nhất của một Bậc Thầy Huấn Luyện!',
        dialogueWin: 'Ngươi... thực sự là BẬC THẦY VĨ ĐẠI NHẤT! Vũ trụ này ghi danh chiến thắng của ngươi!',
        dialogueLose: 'Sức mạnh tâm linh của ta là tuyệt đối và bất bại!',
        bossSkillName: 'Tâm Linh Vô Cực (Psycho Break)',
        bossSkillIcon: '🔮',
        bossSkillDesc: 'Đảo ma trận bảng cờ và khóa 2s',
        bossSkillInterval: 10,
        moveDelayMin: 1000,
        moveDelayMax: 1400,
        rewardCoins: 300,
        targetTime: 140,
        chapterEnvEffect: 'astral-cosmic',
      },
    ],
  },
]

export function getStageById(stageId: number): BossStageConfig | undefined {
  for (const ch of CAMPAIGN_CHAPTERS) {
    const s = ch.stages.find(st => st.stageId === stageId)
    if (s) return s
  }
  return undefined
}

export function getChapterById(chapterId: number): CampaignChapter | undefined {
  return CAMPAIGN_CHAPTERS.find(c => c.id === chapterId)
}
